apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-app1edfs
  janus-idp.io/tekton: go-app1edfs
  backstage.io/kubernetes-id: go-app1edfs
  backstage.io/kubernetes-namespace: go-app1edfs 
  app.kubernetes.io/part-of: go-app1edfs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
